// <auto-generated />
namespace WalkingDinner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class course2program : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course2program));
        
        string IMigrationMetadata.Id
        {
            get { return "202005011319090_course2program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
